# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Pusher' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PusherSwift', git: 'https://github.com/pusher/pusher-websocket-swift.git', branch: ‘single-target-swift-3’

end
